### ISSUE TITLE
Provide an uberjar as an automatic module without split packages

### ISSUE THREAD

**Issue by eusilin** [stefan-zobel/streamsupport#15]
Is it possible to merge streamsupport-cfuture into the main streamsupport jar and publish it on maven repository?
We need to use streamsupport including CompletableFuture in modules that could compile both for java 8 and java 9 environments.
Currently it's ok in java8 but isn't possible in java 9 environment since streamsupport and streamsupport.cfuture automatic modules have split package (they both have java8.util.concurrent package).

**Comment by stefan-zobel** [comment]
Apart from being more modern in terms of supported methods you only have disadvantages by using streamsupport on Java 8 / Java 9 instead of the platform API.

Up to release 1.4 streamsupport has in fact been deployed as one monolithic jar. I've changed that because on Android (which constitutes more than 95% of its user base, the rest being mosty Java 6 deployments) high method counts in an app leads to problems and most users at that time didn't need `CompletableFuture`.

I understand the split packages problem but I'm wondering why you use it on Java 8 / Java 9 anyway? It isn't intended for that kind of use.

**Comment by eusilin** [comment]
I made a mistake, it's actually java 7 and java 10. We have common code that runs on Java 10 and RoboVM that supports only java 7 for the moment. We use streamsupport to take advantage of java 8 streams in RoboVM.

**Comment by stefan-zobel** [comment]
Now, it makes sense. I haven't heard of RoboVM for a long time.

I'll think about creating an additional artifact, `streamsupport-all`, for deployment to Maven Central.
But I can't do that right now (I'm on vacation). Would that be ok for you?

**Comment by eusilin** [comment]
Yes, of course, thank you so much!
Have a good vacation!

**Comment by stefan-zobel** [comment]
Done, it's here:

```xml
<dependency>
    <groupId>net.sourceforge.streamsupport</groupId>
    <artifactId>streamsupport_all</artifactId>
    <version>1.7.3.2</version>
</dependency>
```

It has an `Automatic-Module-Name`: `streamsupport_all` and it's version 1.7.3.**2** because it incorporates some minor improvements since the last 1.7.3. release.

**Comment by eusilin** [comment]
It works! This will help us a lot. Thank you so much!

**Comment by stefan-zobel** [comment]
streamsupport-all, version **1.7.4**, just got deployed to Maven Central
