### ISSUE TITLE
Test Smell: it is not a good practice to introduce nondeterministic randomness in test code

### ISSUE THREAD

**Issue by TestSmell** [stefan-zobel/streamsupport#20]
Hi!

We notice that the random number generator (RNG) is used to produce test code in your project.
For example, a random generator in the test method named ''testSort() '' in ''DoublePrimitiveOpsTests.java''
<img width="650" alt="image" src="https://user-images.githubusercontent.com/110402847/185107670-a54b51a5-102d-4a8f-a942-4f02e08f222e.png">

But generating random data in test code is not a good test practice. Since Using non-deterministic randomized data may lead to unexpected unit test failure and once the test case fails, it is hard to trace what test data causes it.

Solution:
There are two solutions:

set a random seed number for your random generator
using a hash method to generate random data

**Comment by stefan-zobel** [comment]
These tests are OpenJDK code. Cf. https://github.com/openjdk/jdk/tree/master/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/stream

I use the OpenJDK tests - virtually unchanged as accurately as possible.

**Comment by stefan-zobel** [comment]
@TestSmell 
That aside, your understanding that random data should never be used in test code is actually wrong.
It is exactly the point of these tests to use random data, to ensure that as many different sequences as are possible are submitted to the test.
Think about what these tests are testing and what it would mean when a test case fails.

**Comment by TestSmell** [comment]
I don't mean random data should never be used in test code is actually wrong, I mean we'd better use deterministic random numbers in test code. 
For example, set a seed for the random generator. Since it can make developers easier to trace the problem in test code once the test case fails.

**Comment by stefan-zobel** [comment]
@TestSmell 
With a seed we'd always get the same number sequence. That's explicity not what we want here. We want to assert that any arbitrary stream of numbers gets sorted correctly, not just a particular one generated by a seeded RNG. Randomness is a virtue in this case, not a vice.

**Comment by TestSmell** [comment]
I just want to know if your test data can never be reproduced, then how to say your test cases are reliable?
Generally, developers only run test cases once before launching the production code, and thus using a random generator with a seed is obviously a better way.

**Comment by stefan-zobel** [comment]
Tests in OpenJDK are run over and over again. Before any single PR gets integrated into the OpenJDK code base the whole test suite is run in several different configurations which means _all_ tests for the whole JDK are run again and again regardless of how unrelated the PR under consideration is. This project has more than 20.000 tests that are executed several times on different Android platforms and different JDKs (more than 20 platforms over all) before any new release.

The test cases in question are reliable in the sense that a single failure would mean that we've found a bug in the code under test. Using a fixed seed can't achieve that because we would always test against the same sequence which is already known to pass the test from past executions. Using a random sequence in each test run increases the space of test data the code under test has to pass - and that is a good thing.

**Comment by stefan-zobel** [comment]
If it helps, I'd suggest brushing up / googling for QuickCheck and random testing
