### ISSUE TITLE
Please clarify: May this library be included in a closed source app?

### ISSUE THREAD

**Issue by akidee** [stefan-zobel/streamsupport#4]
The library (or at least used classes) will not be linked (as the classpath exception allows) but included as part of the artifact.

**Comment by stefan-zobel** [comment]
Starting at https://github.com/stefan-zobel/streamsupport/blob/master/GPL_ClasspathException#L336 the license says:

"Linking this library statically or dynamically with other modules is making
 a combined work based on this library.  Thus, the terms and conditions of
 the GNU General Public License cover the whole combination.

 As a special exception, the copyright holders of this library give you
 permission to link this library with independent modules to produce an
 executable, regardless of the license terms of these independent modules,
 and to copy and distribute the resulting executable under terms of your
 choice ..."

My understanding is that the "Linking this library **_statically_** or **_dynamically_** ..." part covers the inclusion of Java class files in an application.
And I guess that's how anyone else has interpreted this in the past. I may be wrong though.

**Comment by stefan-zobel** [comment]
Another way to look at it is that the "GPL with CE" license was originally conceived for the "GNU Classpath" project whose artifacts were _designed_ to be _included_ in other runtimes / projects.
See https://en.wikipedia.org/wiki/GNU_Classpath#Uses

Anyway, I couldn't change the license because the code is derived from the OpenJDK code and therefore must use the same license.

See also:

https://github.com/streamsupport/streamsupport/issues/19
https://github.com/streamsupport/streamsupport/issues/10
https://github.com/stefan-zobel/streamsupport/issues/3

Regards,
Stefan

**Comment by akidee** [comment]
Thanks for your clarifications. My current understanding is that you only need to GPL and publish _those_ parts of your code as a module which _essentially build upon_ a GPLd library with CE, like your library. Essentially means: My project makes sense without your library in opposite to your library not making sense without OpenJDK code.

> An independent module is a module which is not derived from or based on this library.

"Based" adds confusion, since any module I write which has your library as a dependency is by definition "based" on it. For the CE addition to make sense "or based" should be left out.
