### ISSUE TITLE
SUGGESTION: example of usage

### ISSUE THREAD

**Issue by DemianTinkiel** [stefan-zobel/streamsupport#6]
Hi.

I am not a 100% clear how this is to be used. Once I add the dependency am I to code against your API instead of native java? if so can you give an example of what that would look like?
typical examples such as

```
 java8.util.J8Arrays.stream
```

**Comment by stefan-zobel** [comment]
Hi Demian,

what problems do you have exactly? Are you already familiar with the Java 8+ Stream API?

There is a very detailed Javadoc of the API: http://www.javadoc.io/doc/net.sourceforge.streamsupport/streamsupport/1.7.0

Did you look at that? And yes, you are expected to program against the **_java8.util_** classes in lieu of the official **_java.util_** API.

I think you'll find that the API differences are quite smallish (that was the main streamsupport design goal). Note that if you are on Android and use Andoid Studio 3+ you could even use the https://github.com/retrostreams/android-retrostreams fork (with package prefix "java9." instead of "java8.") where the API differences are even smaller.

Here is a simple quickstart: https://stackoverflow.com/questions/40886730/filter-a-list-of-objects-in-android-using-gradle-retrolambda-and-lightweight-str/40888879#40888879

As you can see in that example, the most important thing to know is that you usually use the static methods `StreamSupport.stream(Collection c)` or `StreamSupport.parallelStream(Collection c)` to obtain a (sequential or parallel) Stream from a `java.util.Collection`. Once you have a `java8.util.Stream` the usage is almost exactly like in the official API (again, refer to the Javadoc for the details).

There is also an extensive test suite here that can be quite illustrative: https://github.com/stefan-zobel/streamsupport/tree/master/src/tests/java

As an example, here is a test method for the new Java 12 `Collectors.teeing()` method that I've added recently which shows some of the streamsupport API usage:


    @Test(dataProvider = "StreamTestData<Integer>", dataProviderClass = StreamTestDataProvider.class)
    public void testTeeing(String name, TestData.OfRef<Integer> data) throws Exception {
        Collector<Integer, ?, Long> summing = Collectors.summingLong(Integer::valueOf);
        Collector<Integer, ?, Long> counting = Collectors.counting();
        Collector<Integer, ?, Integer> min = collectingAndThen(Collectors.<Integer>minBy(Comparators.naturalOrder()),
                opt -> opt.orElse(Integer.MAX_VALUE));
        Collector<Integer, ?, Integer> max = collectingAndThen(Collectors.<Integer>maxBy(Comparators.naturalOrder()),
                opt -> opt.orElse(Integer.MIN_VALUE));
        Collector<Integer, ?, String> joining = mapping(String::valueOf, Collectors.joining(", ", "[", "]"));

        Collector<Integer, ?, Map.Entry<Long, Long>> sumAndCount = Collectors.teeing(summing, counting, Maps::entry);
        Collector<Integer, ?, Map.Entry<Integer, Integer>> minAndMax = Collectors.teeing(min, max, Maps::entry);
        Collector<Integer, ?, Double> averaging = Collectors.teeing(summing, counting,
                (sum, count) -> ((double)sum) / count);
        Collector<Integer, ?, String> summaryStatistics = Collectors.teeing(sumAndCount, minAndMax,
                (sumCountEntry, minMaxEntry) -> new IntSummaryStatistics(
                        sumCountEntry.getValue(), minMaxEntry.getKey(),
                        minMaxEntry.getValue(), sumCountEntry.getKey()).toString());
        Collector<Integer, ?, String> countAndContent = Collectors.teeing(counting, joining,
                (count, content) -> count+": "+content);

        assertCollect(data, sumAndCount, stream -> {
            List<Integer> list = stream.collect(toList());
            return Maps.entry(StreamSupport.stream(list).mapToLong(Integer::intValue).sum(), (long) list.size());
        });
        assertCollect(data, averaging, stream -> stream.mapToInt(Integer::intValue).average().orElse(Double.NaN));
        assertCollect(data, summaryStatistics,
                stream -> stream.mapToInt(Integer::intValue).summaryStatistics().toString());
        assertCollect(data, countAndContent, stream -> {
            List<Integer> list = stream.collect(toList());
            return list.size() + ": " + list;
        });

        Function<Integer, Integer> classifier = i -> i % 3;
        exerciseMapCollection(data, groupingBy(classifier, sumAndCount),
                new GroupingByAssertion<>(classifier, Map.class,
                        new TeeingAssertion<>(summing, counting, Maps::entry)));
    }


Source: https://github.com/stefan-zobel/streamsupport/blob/master/src/tests/java/org/openjdk/tests/java/util/stream/CollectorsTest.java


Please let me know when you have more specific questions.

Regards,
Stefan

**Comment by stefan-zobel** [comment]
Closing as inactive.
